name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GSC tool
        uses: ./

      - name: Get the output time
        run: gsc-tool
